#!/bin/bash
# Copyright © 2012-2014 Martin Ueding <dev@martin-ueding.de>

# Compile a given LaTeX document with different fonts.

set -u

title="${1%.tex}"

# List the whole thing that goes after ``\includepackage`` here. (Space around
# it make it easy to sort in Vim.)
fonts=(

'[charter]{mathdesign}'
'[garamond]{mathdesign}'
'[math]{anttor}'
'[math]{iwona}'
'[math]{kurier}'
'[urw-garamond]{mathdesign}'
'[utopia]{mathdesign}'
'[varg]{txfonts}'
'{antpolt}'
'{arev}'
'{boisik}'
'{cmbright}'
'{fouriernc}'
'{fourier}'
'{kmath,kerkis}'
'{kpfonts}'
'{lmodern}'
'{mathpazo}'
'{mathpple}'
'{mathptmx}'
'{mathtime}'
'{mbtimes}'
'{millennial}'

)

for font in "${fonts[@]}"
do
    {
        # Compile the document three times to get all the references right. One
        # could just use the ``.aux`` file from the main project to get this
        # right instead. Might be even faster.
        for i in {1..3}
        do
            pdflatex -interaction batchmode -jobname "$title-$font" \
                "\\RequirePackage$font \\input{$title}"
        done

        # Clean up all the other files that ``pdflatex`` generated.
        latexmk -c "$title-$font.log"
    } &
done

wait
